version: '3.3'

services:
  mysql:
    image: mysql:8.0
    restart: 'unless-stopped'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE='daycare'
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD='mysql'
    volumes:
      - /LocalDirectory:/var/lib/mysql
